name: cryptoflow # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Track crypto prices in style with CryptoFlow # 79 char long summary
description: |
  Cryptoflow is an application designed for tracking cryptocurrency prices with an appealing user interface while prioritizing user privacy. It ensures that all requests to the CoinRanking API are proxied, safeguarding personal information and enhancing security. With its intuitive design, Cryptoflow provides users with a seamless experience for monitoring market trends and price fluctuations in the cryptocurrency space.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  cryptoflow:
    source: http://github.com/judemont/cryptoflow
    plugin: flutter